name: Run Simulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run simulation
        run: |
          python simulation.py
          
      - name: Upload simulation results (Optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: simulation-results
          path: results/  # Replace with the directory where your simulation outputs results

      - name: Notify on failure (Optional)
        if: failure()
        uses: softprops/slack-success-failure@v4
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
